stages:
  - build
  - test

build:
  stage: build
  script: 
          - cd ./rentalapp
          - mvn $MAVEN_CLI_OPTS compile

test:
  stage: test
  script:
          - cd ./rentalapp
          - mvn clean test
